In [46]:
import numpy as np 
import pandas as pd

In [47]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [50]:
movies = movies.merge(credits,on='title')

In [51]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [53]:
movies = movies[['cast','overview','crew','title','movie_id','keywords','genres']]

In [54]:
movies.head()

,cast,overview,crew,title,movie_id,keywords,genres
0,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","In the 22nd century, a paraplegic Marine is di...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Avatar,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
1,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","Captain Barbossa, long believed to be dead, ha...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Pirates of the Caribbean: At World's End,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""..."
2,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",A cryptic message from Bond’s past sends him o...,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",Spectre,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
3,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",Following the death of District Attorney Harve...,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",The Dark Knight Rises,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam..."
4,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","John Carter is a war-weary, former military ca...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",John Carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."

In [58]:
movies.isnull().sum()

cast        0
overview    0
crew        0
title       0
movie_id    0
keywords    0
genres      0
dtype: int64

In [57]:
movies.dropna(inplace=True)

In [59]:
movies.duplicated().sum()

0

In [60]:
import ast

In [61]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name']) 
    return L

In [62]:
 movies['genres'] = movies['genres'].apply(convert)

In [63]:
movies.head()

,cast,overview,crew,title,movie_id,keywords,genres
0,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","In the 22nd century, a paraplegic Marine is di...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Avatar,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Action, Adventure, Fantasy, Science Fiction]"
1,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","Captain Barbossa, long believed to be dead, ha...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Pirates of the Caribbean: At World's End,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[Adventure, Fantasy, Action]"
2,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",A cryptic message from Bond’s past sends him o...,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",Spectre,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[Action, Adventure, Crime]"
3,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",Following the death of District Attorney Harve...,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",The Dark Knight Rises,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[Action, Crime, Drama, Thriller]"
4,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","John Carter is a war-weary, former military ca...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",John Carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[Action, Adventure, Science Fiction]"

In [64]:
movies['keywords'] = movies['keywords'].apply(convert)

In [65]:
movies.head()

,cast,overview,crew,title,movie_id,keywords,genres
0,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","In the 22nd century, a paraplegic Marine is di...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Avatar,19995,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]"
1,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","Captain Barbossa, long believed to be dead, ha...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Pirates of the Caribbean: At World's End,285,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]"
2,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",A cryptic message from Bond’s past sends him o...,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",Spectre,206647,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]"
3,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",Following the death of District Attorney Harve...,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",The Dark Knight Rises,49026,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]"
4,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","John Carter is a war-weary, former military ca...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",John Carter,49529,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]"

In [66]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [67]:
movies['cast'] = movies['cast'].apply(convert3)

In [68]:
movies.head()

,cast,overview,crew,title,movie_id,keywords,genres
0,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","In the 22nd century, a paraplegic Marine is di...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Avatar,19995,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]"
1,"[Johnny Depp, Orlando Bloom, Keira Knightley]","Captain Barbossa, long believed to be dead, ha...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Pirates of the Caribbean: At World's End,285,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]"
2,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",A cryptic message from Bond’s past sends him o...,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",Spectre,206647,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]"
3,"[Christian Bale, Michael Caine, Gary Oldman]",Following the death of District Attorney Harve...,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",The Dark Knight Rises,49026,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]"
4,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","John Carter is a war-weary, former military ca...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",John Carter,49529,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]"

In [69]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [70]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [71]:
movies.head()

,cast,overview,crew,title,movie_id,keywords,genres
0,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","In the 22nd century, a paraplegic Marine is di...",[James Cameron],Avatar,19995,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]"
1,"[Johnny Depp, Orlando Bloom, Keira Knightley]","Captain Barbossa, long believed to be dead, ha...",[Gore Verbinski],Pirates of the Caribbean: At World's End,285,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]"
2,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",A cryptic message from Bond’s past sends him o...,[Sam Mendes],Spectre,206647,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]"
3,"[Christian Bale, Michael Caine, Gary Oldman]",Following the death of District Attorney Harve...,[Christopher Nolan],The Dark Knight Rises,49026,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]"
4,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","John Carter is a war-weary, former military ca...",[Andrew Stanton],John Carter,49529,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]"

In [72]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [73]:
movies.head()

,cast,overview,crew,title,movie_id,keywords,genres
0,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[In, the, 22nd, century,, a, paraplegic, Marin...",[James Cameron],Avatar,19995,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]"
1,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[Captain, Barbossa,, long, believed, to, be, d...",[Gore Verbinski],Pirates of the Caribbean: At World's End,285,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]"
2,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[A, cryptic, message, from, Bond’s, past, send...",[Sam Mendes],Spectre,206647,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]"
3,"[Christian Bale, Michael Caine, Gary Oldman]","[Following, the, death, of, District, Attorney...",[Christopher Nolan],The Dark Knight Rises,49026,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]"
4,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[John, Carter, is, a, war-weary,, former, mili...",[Andrew Stanton],John Carter,49529,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]"

In [74]:
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [75]:
movies.head()

,cast,overview,crew,title,movie_id,keywords,genres
0,"[SamWorthington, ZoeSaldana, SigourneyWeaver]","[In, the, 22nd, century,, a, paraplegic, Marin...",[JamesCameron],Avatar,19995,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]"
1,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[Captain, Barbossa,, long, believed, to, be, d...",[GoreVerbinski],Pirates of the Caribbean: At World's End,285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]"
2,"[DanielCraig, ChristophWaltz, LéaSeydoux]","[A, cryptic, message, from, Bond’s, past, send...",[SamMendes],Spectre,206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]"
3,"[ChristianBale, MichaelCaine, GaryOldman]","[Following, the, death, of, District, Attorney...",[ChristopherNolan],The Dark Knight Rises,49026,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]"
4,"[TaylorKitsch, LynnCollins, SamanthaMorton]","[John, Carter, is, a, war-weary,, former, mili...",[AndrewStanton],John Carter,49529,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]"

In [76]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [77]:
movies.head()

,cast,overview,crew,title,movie_id,keywords,genres,tags
0,"[SamWorthington, ZoeSaldana, SigourneyWeaver]","[In, the, 22nd, century,, a, paraplegic, Marin...",[JamesCameron],Avatar,19995,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[Captain, Barbossa,, long, believed, to, be, d...",[GoreVerbinski],Pirates of the Caribbean: At World's End,285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d..."
2,"[DanielCraig, ChristophWaltz, LéaSeydoux]","[A, cryptic, message, from, Bond’s, past, send...",[SamMendes],Spectre,206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send..."
3,"[ChristianBale, MichaelCaine, GaryOldman]","[Following, the, death, of, District, Attorney...",[ChristopherNolan],The Dark Knight Rises,49026,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney..."
4,"[TaylorKitsch, LynnCollins, SamanthaMorton]","[John, Carter, is, a, war-weary,, former, mili...",[AndrewStanton],John Carter,49529,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili..."

In [78]:
new_df = movies[['movie_id','title','tags']]

In [79]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\ameyp\AppData\Local\Temp\ipykernel_9616\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [80]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [81]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\ameyp\AppData\Local\Temp\ipykernel_9616\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [82]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [121]:
import nltk

In [122]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [123]:
def stem(text):
    y = []
    
    for i in text.split():
       y.append(ps.stem(i))

    return " ".join(y)

In [124]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\ameyp\AppData\Local\Temp\ipykernel_9616\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [125]:
import sklearn

In [130]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [131]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [128]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [118]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\ameyp\appdata\local\programs\python\python312\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\ameyp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\ameyp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.4.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\ameyp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2024.4.16)
Requirement already satisfied: tqdm in c:\users\ameyp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.66.2)
Requirement already satisfied: colorama in c:\users\ameyp\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [132]:
from sklearn.metrics.pairwise import cosine_similarity

In [136]:
similarity = cosine_similarity(vectors)

In [137]:
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [143]:
 sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [149]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [150]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [153]:
import pickle

In [154]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [155]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [160]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [161]:
pickle.dump(similarity,open('similarity.pkl','wb'))